### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by niinpatel** [pesto-students/rattle-battle#15]
It is critical that any code that gets integrated with the master branch is thoroughly tested and reviewed. So, we need to have an automated build and testing setup which runs all the tests for every pr we make. 

How should we go about doing this? Your suggestions are welcome. 

Also, I would suggest not to merge anything from now until this issue is resolved.

**Comment by niinpatel** [comment]
I'm trying to add travis ci to the repo. But I think an admin needs to enable it first. Mentioning @nimish-gupta 

![travis yml](https://user-images.githubusercontent.com/31539366/52878421-9792ca80-3182-11e9-9b5b-c38408717e5b.PNG)

**Comment by nimish-gupta** [comment]
@niinpatel how are you getting this error? You just have to add travis.yml in the root repo it will start the build.

**Comment by niinpatel** [comment]
@nimish-gupta I'll fix it. Its because the root directory's package.json also doesn't have test script. Once I add that, it should work.
