### ISSUE TITLE
Server is sending incorrect error messages when I call /api/signup

### ISSUE THREAD

**Issue by niinpatel** [pesto-students/rattle-battle#48]
**Case 1:** 
When I call `/api/signup` with a valid email and password but leave out the username the response I get is: 

```js
{ "errors": "Something went wrong while signing up." }
``` 
with status code 500, 

**expected something like:** 

```js
 "errors": [
        {
            "param": "username",
            "msg": "username is required"
        }
    ]
```
with a correct status code.

**Case 2:** 
If I try to sign up with an email or username that is taken it gives me following error message. 
```js
{
    "errors": "Username/E-Mail is taken."
}
```

**expected:** 
It should tell  exactly what needs to be changed, username or email or both. maybe an array of errors would be better suited instead of a string. somthing like: 

```js
 "errors": [
        {
            "param": "username",
            "msg": "username is taken"
        },
       {
            "param": "email",
            "msg": "email is taken"
        }
    ]
```

**Comment by prakhar1912** [comment]
@niinpatel Postman result from Case 1:

![screenshot from 2019-02-23 21-26-11](https://user-images.githubusercontent.com/20063271/53288708-b19b6100-37b1-11e9-9f20-f4650dcd1ad1.png)

**Comment by niinpatel** [comment]
> @niinpatel Postman result from Case 1:
> 
> ![screenshot from 2019-02-23 21-26-11](https://user-images.githubusercontent.com/20063271/53288708-b19b6100-37b1-11e9-9f20-f4650dcd1ad1.png)

Are you sure you're testing on the current master branch on remote? I checked the code and the `userValidator.js` file says username set as optional, then mongodb throws an error which triggers 500 status code response.

https://github.com/pesto-students/rattle-battle/blob/f6ddb2cf8d9e1dd674a0c11ee93d6e33a89dfc1f/server/src/validators/userValidator.js#L8

**Comment by prakhar1912** [comment]
> > @niinpatel Postman result from Case 1:
> > ![screenshot from 2019-02-23 21-26-11](https://user-images.githubusercontent.com/20063271/53288708-b19b6100-37b1-11e9-9f20-f4650dcd1ad1.png)
> 
> Are you sure you're testing on the current master branch on remote? I checked the code and the `userValidator.js` file says username set as optional, then mongodb throws an error which triggers 500 status code response.
> 
> [rattle-battle/server/src/validators/userValidator.js](https://github.com/pesto-students/rattle-battle/blob/f6ddb2cf8d9e1dd674a0c11ee93d6e33a89dfc1f/server/src/validators/userValidator.js#L8)
> 
> Line 8 in [f6ddb2c](/pesto-students/rattle-battle/commit/f6ddb2cf8d9e1dd674a0c11ee93d6e33a89dfc1f)
> 
>  .optional()

Oh okay. My bad. I was testing on the `login-api` branch. I have changed the validator in that. Please wait for the PR to be approved before proceeding.

**Comment by niinpatel** [comment]
Okay!

**Comment by prakhar1912** [comment]
@niinpatel For Case 2, I think it would be better if validation of the email and username took place after the  user is done typing them in, and not when the form is submitted. Thoughts?

**Comment by niinpatel** [comment]
On the client side we can only validate things like length and valid characters are present.  But to check if user already present in database, we'll have to send to it server anyway.

**Comment by prakhar1912** [comment]
> On the client side we can only validate things like length and valid characters are present. But to check if user already present in database, we'll have to send to it server anyway.

Yeah, so we can just make a call to an endpoint to validate the fields when the input is blurred. I have seen a lot of forms do that.

**Comment by niinpatel** [comment]
To do that. we'll have to make an api endpoint called /api/validateinput or something, For our project lets not worry about that. we can implement that feature at a later point. the main aim right now is to get the game and leaderboard working.

**Comment by prakhar1912** [comment]
> To do that. we'll have to make an api endpoint called `/api/validateinput` or something, For our project lets not worry about that. we can implement that feature at a later point. the main aim right now is to get the game and leaderboard working.

Okay. I will make a PR for this after the Login PR has been merged. That works?

**Comment by niinpatel** [comment]
Sure.
